import { Inbox as SubmissionIcon } from "lucide-react";
import { defineField, defineType } from "sanity";
import { DOCUMENT_TYPES } from "../../config/constants";

/**
 * A contact form submission. Generated by the app, never authored: every
 * field is read-only and the type is hidden from the "new document" menu.
 */
export const submission = defineType({
  name: DOCUMENT_TYPES.submission,
  title: "Submission",
  type: "document",
  icon: SubmissionIcon,
  readOnly: true,
  fields: [
    defineField({
      name: "name",
      title: "Name",
      type: "string",
      readOnly: true,
    }),
    defineField({
      name: "email",
      title: "Email",
      type: "string",
      readOnly: true,
    }),
    defineField({
      name: "message",
      title: "Message",
      type: "text",
      rows: 6,
      readOnly: true,
    }),
    defineField({
      name: "page",
      title: "Sent from",
      type: "string",
      description: "Path of the page the form was on",
      readOnly: true,
    }),
    defineField({
      name: "userAgent",
      title: "User agent",
      type: "string",
      readOnly: true,
    }),
    defineField({
      name: "receivedAt",
      title: "Received at",
      type: "datetime",
      readOnly: true,
    }),
  ],
  orderings: [
    {
      name: "receivedAtDesc",
      title: "Newest first",
      by: [{ field: "receivedAt", direction: "desc" }],
    },
  ],
  preview: {
    select: { name: "name", email: "email", receivedAt: "receivedAt" },
    prepare({ name, email, receivedAt }) {
      const date = receivedAt
        ? new Date(receivedAt).toLocaleString("en-GB")
        : "Unknown date";
      return { title: name || email || "Anonymous", subtitle: date };
    },
  },
});
